### ISSUE TITLE
Table 'minecraft.sttowns_errors' doesn't exist

### ISSUE THREAD

**Issue by cyberkeiler** [ShepherdJerred/stTowns#3]
This error is shown in the Log. And yes indeed, only theses tables were created:

   +------------------------------+
   | Tables_in_minecraft             |
   +------------------------------+
   | sttowns_nation_flags         |
| sttowns_nation_relationships |
| sttowns_nation_town_invites  |
| sttowns_nation_towns         |
| sttowns_nations              |
| sttowns_player_flags         |
| sttowns_player_messages      |
| sttowns_players              |
| sttowns_plot_flags           |
| sttowns_plot_permissions     |
| sttowns_plot_players         |
| sttowns_plots                |
| sttowns_town_flags           |
| sttowns_town_player_invites  |
| sttowns_towns                |
+------------------------------+

**Comment by ShepherdJerred** [comment]
I'll check it when I get home from work, thanks!

**Comment by cyberkeiler** [comment]
Thx a lot. Looking forward to check this out ;)

**Comment by ShepherdJerred** [comment]
Can you put debug: true in your config.yml, and then start up your server and give me the log?

**Comment by cyberkeiler** [comment]
The relevant part:

> ...
[14:55:35] [Server thread/INFO]: Preparing start region for level 2 (Seed: 799144384906325339)
[14:55:35] [Server thread/INFO]: [stTowns] Enabling stTowns v2.0.1
[14:55:35] [Server thread/WARN]: [Server thread] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
[14:55:35] [Server thread/INFO]: [stTowns] Connection to MySQL database was successful!
[14:55:35] [Server thread/INFO]: [stTowns] Tables don't exist, creating them now
[14:55:35] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'error_date'
[14:55:35] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:55:35] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:55:35] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:55:35] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
[14:55:35] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[14:55:35] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[14:55:35] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[14:55:35] [Server thread/WARN]: 	at com.shepherdjerred.sttowns.mysql.QueryHelper.runUpdate(QueryHelper.java:43)
[14:55:35] [Server thread/WARN]: 	at com.shepherdjerred.sttowns.mysql.QueryHelper.massRunUpdates(QueryHelper.java:69)
[14:55:35] [Server thread/WARN]: 	at com.shepherdjerred.sttowns.mysql.TableManager.lambda$loadDatabase$0(TableManager.java:97)
[14:55:35] [Server thread/WARN]: 	at com.shepherdjerred.sttowns.mysql.QueryManager.checkTables(QueryManager.java:546)
[14:55:35] [Server thread/WARN]: 	at com.shepherdjerred.sttowns.mysql.TableManager.loadDatabase(TableManager.java:117)
[14:55:35] [Server thread/WARN]: 	at com.shepherdjerred.sttowns.Main.onEnable(Main.java:45)
[14:55:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[14:55:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:55:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:55:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[14:55:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[14:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416)
[14:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381)
[14:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336)
[14:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270)
[14:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539)
[14:55:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[14:55:35] [Server thread/INFO]: [stTowns] Nations base data loaded
[14:55:35] [Server thread/INFO]: [stTowns] Towns loaded
[14:55:35] [Server thread/INFO]: [stTowns] Nations towns loaded
[14:55:35] [Server thread/INFO]: [stTowns] Plot data loaded

**Comment by ShepherdJerred** [comment]
What version of MySQL are you running?

**Comment by ShepherdJerred** [comment]
Closing the issue, use MySQL 5.6.5

**Comment by cyberkeiler** [comment]
Thanks - updated now and error disappeared. ;)
